FROM ghcr.io/astral-sh/uv:0.9.30 AS uv

FROM mcr.microsoft.com/devcontainers/python:3-3.13

COPY --from=uv --chown=vscode: /uv /uvx /bin/

RUN \
    apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        # Additional library needed by some tests and accordingly by VScode Tests Discovery
        git \
        cmake \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /workspaces
